title: Responsible AI Collaborative
logo: /assets/img/logo.png
description: The convening body for the AI Incident Database
show_downloads: true
google_analytics: G-C6ZZD72QY2
theme: jekyll-theme-minimal
